### ISSUE TITLE
大佬TVB无线财经资讯看不了

### ISSUE THREAD

**Issue by xh0823** [l821706/IPTV#1]
大佬TVB无线财经资讯看不了

**Comment by l821706** [comment]
已更新，个人私有仓，还以为没人看呢......


PK就怕乱发型
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l821706/IPTV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月28日(星期天) 凌晨0:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[l821706/IPTV] 大佬TVB无线财经资讯看不了 (Issue #1)





 
大佬TVB无线财经资讯看不了

**Comment by l821706** [comment]
已更新，个人私有仓，还以为没人看呢......

**Comment by xh0823** [comment]
好的 谢谢大佬了
